# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktype',
            name='no_of_wall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ktype',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ktype',
            name='thumbnails',
            field=models.ImageField(default='kitchen/images/kitchen_types/thumbnail.jpg', upload_to='kitchen/images/kitchen_types/'),
        ),
    ]
