# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktheme',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Theme Name'),
        ),
        migrations.AlterField(
            model_name='ktheme',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchen',
            unique_together=set([('theme', 'slug', 'l', 'b', 'h')]),
        ),
        migrations.AlterUniqueTogether(
            name='ktheme',
            unique_together=set([('type', 'slug')]),
        ),
    ]
