# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kappliances',
            options={'verbose_name': 'Kitchen Apliance', 'verbose_name_plural': 'Kitchen Appliances'},
        ),
        migrations.AlterModelOptions(
            name='kincludes',
            options={'verbose_name': 'Kitchen Include', 'verbose_name_plural': 'Kitchen Includes'},
        ),
        migrations.AlterModelOptions(
            name='ktype',
            options={'verbose_name': 'Kitchen Type', 'verbose_name_plural': 'Kitchen_Types'},
        ),
        migrations.AlterModelTable(
            name='kappliances',
            table='core_kitchen_appliance',
        ),
        migrations.AlterModelTable(
            name='kincludes',
            table='core_kitchen_include',
        ),
    ]
