# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170113_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kappliance',
            options={'ordering': ('name', 'kitchen'), 'verbose_name': 'Kitchen Apliance', 'verbose_name_plural': 'Kitchen Appliances'},
        ),
        migrations.AlterModelOptions(
            name='kmaterial',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Kitchen material', 'verbose_name_plural': 'Kitchen Materials'},
        ),
    ]
