# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170104_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KFinish',
            new_name='KFinishing',
        ),
        migrations.AlterModelOptions(
            name='kfinishing',
            options={'verbose_name': 'Kitchen Finishing', 'verbose_name_plural': 'Kitchen Finishings'},
        ),
        migrations.AlterModelOptions(
            name='kmaterial',
            options={'verbose_name': 'Kitchen material', 'verbose_name_plural': 'Kitchen Materials'},
        ),
        migrations.AlterModelTable(
            name='kfinishing',
            table='core_kitchen_finishing',
        ),
        migrations.AlterModelTable(
            name='kmaterial',
            table='core_Kitchen material',
        ),
    ]
