# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170118_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Theme Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('image', models.ImageField(upload_to='kitchen/images/kitchen_themes/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('k_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_type', to='core.KType')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_kitchen_theme',
                'verbose_name': 'Kitchen Theme',
                'verbose_name_plural': 'Kitchen Themes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ktheme',
            unique_together=set([('k_type', 'slug')]),
        ),
    ]
