# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170104_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kcolor',
            options={'verbose_name': 'Kitchen Color', 'verbose_name_plural': 'Kitchen Colors'},
        ),
        migrations.AlterModelOptions(
            name='kimage',
            options={'verbose_name': 'Kitchen Image', 'verbose_name_plural': 'Kitchen Images'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'Kitchen', 'verbose_name_plural': 'Kitchens'},
        ),
        migrations.AlterModelOptions(
            name='koption',
            options={'verbose_name': 'Kitchen Options', 'verbose_name_plural': 'Kitchen Options'},
        ),
        migrations.AlterModelTable(
            name='kcolor',
            table='core_kitchen_color',
        ),
        migrations.AlterModelTable(
            name='kimage',
            table='core_kitchen_image',
        ),
        migrations.AlterModelTable(
            name='kitchen',
            table='core_kitchen',
        ),
        migrations.AlterModelTable(
            name='kmaterial',
            table='core_kitchen_material',
        ),
        migrations.AlterModelTable(
            name='koption',
            table='core_kitchen_option',
        ),
    ]
