# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170113_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ktheme',
            old_name='type',
            new_name='k_type',
        ),
        migrations.AlterUniqueTogether(
            name='ktheme',
            unique_together=set([('k_type', 'slug')]),
        ),
    ]
