# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kitchen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['name', 'theme'], 'verbose_name': 'Kitchen', 'verbose_name_plural': 'Kitchens'},
        ),
        migrations.AlterUniqueTogether(
            name='kitchen',
            unique_together=set([('theme', 'slug', 'l', 'b', 'h')]),
        ),
        migrations.AlterModelTable(
            name='kitchen',
            table='core_kitchen',
        ),
    ]
