# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170104_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kimage',
            name='k_option',
        ),
        migrations.AlterModelOptions(
            name='kappliance',
            options={'ordering': ['name', 'kitchen'], 'verbose_name': 'Kitchen Apliance', 'verbose_name_plural': 'Kitchen Appliances'},
        ),
        migrations.AlterModelOptions(
            name='kcolor',
            options={'ordering': ['name'], 'verbose_name': 'Kitchen Color', 'verbose_name_plural': 'Kitchen Colors'},
        ),
        migrations.AlterModelOptions(
            name='kfinishing',
            options={'ordering': ['name'], 'verbose_name': 'Kitchen Finishing', 'verbose_name_plural': 'Kitchen Finishings'},
        ),
        migrations.AlterModelOptions(
            name='kincludes',
            options={'ordering': ['kitchen', 'name', 'brand'], 'verbose_name': 'Kitchen Include', 'verbose_name_plural': 'Kitchen Includes'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['name', 'type'], 'verbose_name': 'Kitchen', 'verbose_name_plural': 'Kitchens'},
        ),
        migrations.AlterModelOptions(
            name='kmaterial',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Kitchen material', 'verbose_name_plural': 'Kitchen Materials'},
        ),
        migrations.AlterModelOptions(
            name='koption',
            options={'ordering': ['kitchen', 'material', 'finish', 'color'], 'verbose_name': 'Kitchen Options', 'verbose_name_plural': 'Kitchen Options'},
        ),
        migrations.AlterModelOptions(
            name='ktype',
            options={'ordering': ['name'], 'verbose_name': 'Kitchen Type', 'verbose_name_plural': 'Kitchen Types'},
        ),
        migrations.AlterField(
            model_name='ktype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Type Name'),
        ),
        migrations.DeleteModel(
            name='KImage',
        ),
    ]
