# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170106_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='KImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchen_images/')),
                ('k_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kithen_image', to='core.KColor')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='core.Kitchen')),
            ],
            options={
                'ordering': ['kitchen', 'k_color'],
                'db_table': 'core_kitchen_image',
                'verbose_name': 'Kitchen Image',
                'verbose_name_plural': 'Kitchen Images',
            },
        ),
        migrations.RemoveField(
            model_name='koption',
            name='color',
        ),
        migrations.RemoveField(
            model_name='koption',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='koption',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='koption',
            name='material',
        ),
        migrations.DeleteModel(
            name='KOption',
        ),
    ]
