# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170118_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='kitchen/images/kitchen_appliances/')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kitchen')),
            ],
            options={
                'ordering': ['kitchen', 'category', 'brand'],
                'db_table': 'core_kitchen_include',
                'verbose_name': 'Kitchen Include',
                'verbose_name_plural': 'Kitchen Includes',
            },
        ),
    ]
