# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170113_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktheme',
            name='k_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_type', to='core.KType'),
        ),
    ]
