# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170106_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcolor',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
