# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kincludes'),
    ]

    operations = [
        migrations.CreateModel(
            name='KISub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=30)),
                ('is_inculded', models.BooleanField(default=True)),
                ('k_includes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KIncludes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
