# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170113_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
    ]
