# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kisub'),
    ]

    operations = [
        migrations.CreateModel(
            name='KAppliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='kitchen/images/kitchen_appliances/')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kitchen')),
            ],
            options={
                'ordering': ('name', 'kitchen'),
                'db_table': 'core_kitchen_appliance',
                'verbose_name': 'Kitchen Appliance',
                'verbose_name_plural': 'Kitchen Appliances',
            },
        ),
        migrations.AlterUniqueTogether(
            name='kappliance',
            unique_together=set([('kitchen', 'name')]),
        ),
    ]
