# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170113_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktype',
            name='image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
