# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170106_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAppliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ['name', 'wardrobe'],
                'db_table': 'core_wardrobe_appliance',
                'verbose_name': 'Wardrobe Apliance',
                'verbose_name_plural': 'Wardrobe Appliances',
            },
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('l', models.IntegerField()),
                ('b', models.IntegerField()),
                ('h', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'type'],
                'db_table': 'core_wardrobe',
                'verbose_name': 'Wardrobe',
                'verbose_name_plural': 'Wardrobe',
            },
        ),
        migrations.CreateModel(
            name='WColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=b'')),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_wardrobe_color',
                'verbose_name': 'Wardrobe Color',
                'verbose_name_plural': 'Wardrobe Colors',
            },
        ),
        migrations.CreateModel(
            name='WFinishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_wardrobe_finishing',
                'verbose_name': 'Wardrobe Finishing',
                'verbose_name_plural': 'Wardrobe Finishings',
            },
        ),
        migrations.CreateModel(
            name='WImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe_images/')),
                ('w_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_image', to='core.WColor')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to='core.Wardrobe')),
            ],
            options={
                'ordering': ['wardrobe', 'w_color'],
                'db_table': 'core_wardrobe_image',
                'verbose_name': 'Wardrobe Image',
                'verbose_name_plural': 'Wardrobe Images',
            },
        ),
        migrations.CreateModel(
            name='WIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('items', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=b'')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wardrobe')),
            ],
            options={
                'ordering': ['wardrobe', 'name', 'brand'],
                'db_table': 'core_wardrobe_include',
                'verbose_name': 'Wardrobe Include',
                'verbose_name_plural': 'Wardrobe Includes',
            },
        ),
        migrations.CreateModel(
            name='WMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'price'],
                'db_table': 'core_wardrobe_material',
                'verbose_name': 'Wardrobe material',
                'verbose_name_plural': 'Wardrobe Materials',
            },
        ),
        migrations.CreateModel(
            name='WType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Type Name')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_wardrobe_type',
                'verbose_name': 'wardrobe Type',
                'verbose_name_plural': 'Wardrobe Types',
            },
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='core.WType'),
        ),
        migrations.AddField(
            model_name='wappliance',
            name='wardrobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wardrobe'),
        ),
    ]
