# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170118_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ('name', 'price'),
                'db_table': 'core_kitchen_material',
                'verbose_name': 'Kitchen material',
                'verbose_name_plural': 'Kitchen Materials',
            },
        ),
    ]
