# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ktype_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kappliance',
            unique_together=set([('kitchen', 'name')]),
        ),
    ]
