# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170106_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='b',
            field=models.IntegerField(verbose_name='breadth'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='h',
            field=models.IntegerField(verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='l',
            field=models.IntegerField(verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='b',
            field=models.IntegerField(verbose_name='breadth'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='h',
            field=models.IntegerField(verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='l',
            field=models.IntegerField(verbose_name='length'),
        ),
    ]
