# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kfinishing'),
    ]

    operations = [
        migrations.CreateModel(
            name='KColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='kitchen/images/kitchen_color/')),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_kitchen_color',
                'verbose_name': 'Kitchen Color',
                'verbose_name_plural': 'Kitchen Colors',
            },
        ),
    ]
