# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_kimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmaterial',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Kitchen Material', 'verbose_name_plural': 'Kitchen Materials'},
        ),
    ]
