# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170118_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisub',
            options={'ordering': ('k_includes', 'sub_category'), 'verbose_name': 'Kitchen Includes Sub-Category', 'verbose_name_plural': 'Kitchen Includes Sub-Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='kisub',
            unique_together=set([('k_includes', 'sub_category')]),
        ),
        migrations.AlterModelTable(
            name='kisub',
            table='core_kitchen_includes_sub_category',
        ),
    ]
