# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170118_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='WType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Type Name')),
                ('image', models.ImageField(upload_to='wardrobe/images/wardrobe_types/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'core_wardrobe_type',
                'verbose_name': 'Wardrobe Type',
                'verbose_name_plural': 'Wardrobe Types',
            },
        ),
    ]
