# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170116_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wappliance',
            name='wardrobe',
        ),
        migrations.RemoveField(
            model_name='wardrobe',
            name='type',
        ),
        migrations.DeleteModel(
            name='WFinishing',
        ),
        migrations.RemoveField(
            model_name='wimage',
            name='w_color',
        ),
        migrations.RemoveField(
            model_name='wimage',
            name='wardrobe',
        ),
        migrations.RemoveField(
            model_name='wincludes',
            name='wardrobe',
        ),
        migrations.DeleteModel(
            name='WMaterial',
        ),
        migrations.AlterField(
            model_name='kappliance',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_appliances/'),
        ),
        migrations.AlterField(
            model_name='kcolor',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_color/'),
        ),
        migrations.AlterField(
            model_name='kimage',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_images/'),
        ),
        migrations.AlterField(
            model_name='kincludes',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_appliances/'),
        ),
        migrations.AlterField(
            model_name='ktheme',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_themes/'),
        ),
        migrations.AlterField(
            model_name='ktype',
            name='image',
            field=models.ImageField(upload_to='kitchen/images/kitchen_types/'),
        ),
        migrations.DeleteModel(
            name='WAppliance',
        ),
        migrations.DeleteModel(
            name='Wardrobe',
        ),
        migrations.DeleteModel(
            name='WColor',
        ),
        migrations.DeleteModel(
            name='WImage',
        ),
        migrations.DeleteModel(
            name='WIncludes',
        ),
        migrations.DeleteModel(
            name='WType',
        ),
    ]
