# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170116_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcolor',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
