# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170118_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='wardrobe/images/wardrobe_appliances/')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wardrobe')),
            ],
            options={
                'ordering': ['wardrobe', 'category', 'brand'],
                'db_table': 'core_wardrobe_include',
                'verbose_name': 'Wardrobe Include',
                'verbose_name_plural': 'Wardrobe Includes',
            },
        ),
    ]
