# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wincludes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WISub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=30)),
                ('is_inculded', models.BooleanField(default=True)),
                ('w_includes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WIncludes')),
            ],
            options={
                'ordering': ('w_includes', 'sub_category'),
                'db_table': 'core_wardrobe_includes_sub_category',
                'verbose_name': 'Wardrobe Includes Sub-Category',
                'verbose_name_plural': 'Wardrobe Includes Sub-Categories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wisub',
            unique_together=set([('w_includes', 'sub_category')]),
        ),
    ]
