# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170118_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAppliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='wardrobe/images/wardrobe_appliances/')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wardrobe')),
            ],
            options={
                'ordering': ('name', 'wardrobe'),
                'db_table': 'core_wardrobe_appliance',
                'verbose_name': 'Wardrobe Appliance',
                'verbose_name_plural': 'Wardrobe Appliances',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wappliance',
            unique_together=set([('wardrobe', 'name')]),
        ),
    ]
