# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_wcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/images/wardrobe_images/')),
                ('w_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_image', to='core.WColor')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to='core.Wardrobe')),
            ],
            options={
                'ordering': ['wardrobe', 'w_color'],
                'db_table': 'core_wardrobe_image',
                'verbose_name': 'Kitchen Image',
                'verbose_name_plural': 'Wardrobe Images',
            },
        ),
    ]
