# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_kitchenform'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KColor')),
                ('finishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KFinishing')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kitchen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KMaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='KitchenForm',
            new_name='WardrobeRequest',
        ),
    ]
