# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170119_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenrequest',
            name='color',
        ),
        migrations.RemoveField(
            model_name='kitchenrequest',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='kitchenrequest',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='kitchenrequest',
            name='material',
        ),
        migrations.RemoveField(
            model_name='wardroberequest',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wardroberequest',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='wardroberequest',
            name='material',
        ),
        migrations.RemoveField(
            model_name='wardroberequest',
            name='wardrobe',
        ),
        migrations.DeleteModel(
            name='KitchenRequest',
        ),
        migrations.DeleteModel(
            name='WardrobeRequest',
        ),
    ]
