# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170119_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WardrobeRequest',
            new_name='WardrobeReponse',
        ),
    ]
