# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170119_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisub',
            old_name='is_inculded',
            new_name='is_included',
        ),
    ]
