# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170120_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='kincludes',
            name='size',
            field=models.CharField(default='1*2*3', max_length=20),
        ),
    ]
