# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_kincludes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenresponse',
            name='color',
        ),
        migrations.RemoveField(
            model_name='kitchenresponse',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='kitchenresponse',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='kitchenresponse',
            name='material',
        ),
        migrations.RemoveField(
            model_name='wardrobereponse',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wardrobereponse',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='wardrobereponse',
            name='material',
        ),
        migrations.RemoveField(
            model_name='wardrobereponse',
            name='wardrobe',
        ),
        migrations.RenameField(
            model_name='wisub',
            old_name='is_inculded',
            new_name='is_included',
        ),
        migrations.RemoveField(
            model_name='kincludes',
            name='size',
        ),
        migrations.DeleteModel(
            name='KitchenResponse',
        ),
        migrations.DeleteModel(
            name='WardrobeReponse',
        ),
    ]
