# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170131_0650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wappliance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wappliance',
            name='wardrobe',
        ),
        migrations.RemoveField(
            model_name='wincludes',
            name='wardrobe',
        ),
        migrations.AlterUniqueTogether(
            name='wisub',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wisub',
            name='w_includes',
        ),
        migrations.DeleteModel(
            name='WAppliance',
        ),
        migrations.DeleteModel(
            name='WIncludes',
        ),
        migrations.DeleteModel(
            name='WISub',
        ),
    ]
